### ISSUE TITLE
Crash on restore WeekState

### ISSUE THREAD

**Issue by petrstetka** [boguszpawlowski/ComposeCalendar#123]
App is crashing when using **StaticWeekCalendar** on restore state
```
java.time.format.DateTimeParseException: Text 'Week(days=[2024-08-12, 2024-08-13, 2024-08-14, 2024-08-15, 2024-...' could not be parsed at index 0
at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2050)
at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1952)
at java.time.LocalDate.parse(LocalDate.java:425)
at java.time.LocalDate.parse(LocalDate.java:410)
at io.github.boguszpawlowski.composecalendar.header.WeekState$Companion$Saver$2.invoke(WeekState.kt:43)
at io.github.boguszpawlowski.composecalendar.header.WeekState$Companion$Saver$2.invoke(WeekState.kt:33)
at androidx.compose.runtime.saveable.MapSaverKt$mapSaver$2.invoke(MapSaver.kt:52)
at androidx.compose.runtime.saveable.MapSaverKt$mapSaver$2.invoke(MapSaver.kt:33)
at androidx.compose.runtime.saveable.SaverKt$Saver$1.restore(Saver.kt:68)
at androidx.compose.runtime.saveable.RememberSaveableKt.rememberSaveable(RememberSaveable.kt:87)
at io.github.boguszpawlowski.composecalendar.WeekCalendarKt.rememberWeekCalendarState(WeekCalendar.kt:256)
```

**Comment by sankari-erika** [comment]
Hi @boguszpawlowski,
Do you have plans on making a new release in the near future? Would love to have this fix 😊

**Comment by boguszpawlowski** [comment]
@sankari-erika Deployed in 1.4.0 just now! Sorry fot the delay, there were some issues with publishing the new version!
